// <auto-generated />
namespace RepositoryNAuthenticaiton.Migrations.SchoolContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FullDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201803031748425_FullDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
